FROM node:24-alpine

WORKDIR /YellowBook/development/backend

ADD development/backend/package.json /YellowBook/development/backend

RUN yarn install

ADD development/backend/ /YellowBook/development/backend

RUN chmod +x entrypoint.sh

EXPOSE 8085

CMD ["/bin/bash", "./entrypoint.sh"]