FROM node:22-alpine

WORKDIR /YellowBook/development/backend

ADD development/backend/package.json /YellowBook/development/backend

RUN yarn install

ADD development/backend/ /YellowBook/development/backend

EXPOSE 8085

CMD ["yarn", "start"]