FROM node:24-alpine

WORKDIR /YellowBook/development/frontend

ADD development/frontend/package*.json /YellowBook/development/frontend/

RUN yarn install

ADD development/frontend/ /YellowBook/development/frontend/

EXPOSE 3000

CMD [ "yarn","dev" ]
