FROM node:22-alpine AS build

WORKDIR /YellowBook/development/frontend

ADD development/frontend/package*.json /YellowBook/development/frontend/

RUN yarn install

ADD development/frontend/ /YellowBook/development/frontend/

RUN yarn build

EXPOSE 80

CMD [ "yarn","dev" ]
